### ISSUE TITLE
Fix "Generate Docs" action

### ISSUE THREAD

**Issue by snowspike** [spellshape/cli#16]

**Comment by joshLong145** [comment]
From looking at the logs of the failed runs it seems there is an issue with the current token used in the action pipelines the following was reported from the `gen docs` action:
`error while loading plugins: fail to link: github.com/spellshape/cli-plugin-network@main: cloning "github.com/spellshape/cli-plugin-network@main": authentication required`
This can be resolved by updating the token within the repository secrets by an admin

**Comment by snowspike** [comment]
@joshLong145 the `authentication required` was because the repo was private. Now we're getting the following error:

https://github.com/spellshape/cli/actions/runs/4185279151/jobs/7252098794

**Comment by snowspike** [comment]
For some reason, even though the plugin get compiled without errors, when it gets added to the CLI, I get this error.

**Comment by joshLong145** [comment]
> For some reason, even though the plugin gets compiled without errors, when it gets added to the CLI, I get this error.

I've seen these kind of errors before while developing some of the plugin features. I might know what's going on. Will take a look

**Comment by joshLong145** [comment]
> @joshLong145 the `authentication required` was because the repo was private. Now we're getting the following error:
> 
> https://github.com/spellshape/cli/actions/runs/4185279151/jobs/7252098794
> 
> ```
> Error: -15T15:13:11.908Z [ERROR] plugin github.com/spellshape/cli-plugin-network@main: plugin process exited: path=/tmp/.spellshape3413486188/plugins/github.com/spellshape/cli-plugin-network-main/cli-plugin-network pid=7502 error="exit status 2"
> Path 						Status 	Config 	
> github.com/spellshape/cli-plugin-network@main 	✘ Error: connecting: Unrecognized remote plugin message: 
> 
> This usually means that the plugin is either invalid or simply
> needs to be recompiled to support the latest protocol. 	global 	
> 
> 2023/02/15 15:13:11 error while loading plugins: fail to link: github.com/spellshape/cli-plugin-network@main: connecting: Unrecognized remote plugin message: 
> 
> This usually means that the plugin is either invalid or simply
> needs to be recompiled to support the latest protocol.
> exit status 1
> ```

After some investigation there is an error reported from the `cli-plugin-network` binary which is `"exit status 2"` after attempting to stand up the plugin from a local build it seems to be related to `ibc-go` below is a stack trace for further context: 
```
panic: error with code 2 is already registered: "invalid identifier"

goroutine 1 [running]:
cosmossdk.io/errors.RegisterWithGRPCCode({0x104294aba, 0x4}, 0x2, 0x2, {0x1042e33f4, 0x12})
	/Users/bean/go/pkg/mod/cosmossdk.io/errors@v1.0.0-beta.7/errors.go:41 +0x264
cosmossdk.io/errors.Register({0x104294aba?, 0x0?}, 0x3ed998?, {0x1042e33f4?, 0x104ea2a40?})
	/Users/bean/go/pkg/mod/cosmossdk.io/errors@v1.0.0-beta.7/errors.go:33 +0x30
github.com/cosmos/ibc-go/v5/modules/core/24-host.init()
	/Users/bean/go/pkg/mod/github.com/cosmos/ibc-go/v5@v5.1.0/modules/core/24-host/errors.go:12 +0x48
```

being that this now seems be an issue in the `cli-network-plugin` im thinking we migrate this to its own issue on it's Repo.
